### ISSUE TITLE
Listing top level flags with 'main flags' not working

### ISSUE THREAD

**Issue by tkivisik** [loov/goda#17]
## What?
`goda` help message says: "Use "goda flags" for a list of top-level flags", but typing that does not show any flag info.

## Replicate
```bash
go build
goda flags
```

## Expected
Some flag info

## Got
Same help as when just typing `goda`

**Comment by egonelbre** [comment]
I don't think I'm unable to get that "Use "goda flags" for a list of top-level flags" message, maybe some change ensured that it's not being shown?

**Comment by egonelbre** [comment]
I don't think I'm unable to get that "Use "goda flags" for a list of top-level flags" message, maybe some change ensured that it's not being shown?
