### ISSUE TITLE
command `nm` unintuitive

### ISSUE THREAD

**Issue by tkivisik** [loov/goda#18]
From the list of subcommands, `nm` is the one which could have a more intuitive name. Depending on future developments I would recommend `binary` or `memory` as a replacement.

**Comment by egonelbre** [comment]
`go tool nm` and a similar tool from linux `nm`, but I agree, there should be a better name for it.

**Comment by tkivisik** [comment]
If you say that tool will primarily be used by people who know what `go tool nm` and linux `nm` are, then keeping the name `nm` has value. For newcomers, docs should be helpful and explicit.

**Comment by egonelbre** [comment]
The target is to make `nm` more helpful rather than just outputting the raw information. I think there's no good argument in why to keep calling it `nm`. While I was writing it, I just couldn't figure out a better name.

**Comment by egonelbre** [comment]
I just realized that it could be called `weight` similarly to `goweight` tool.
