### ISSUE TITLE
Function `sat8` name unclear

### ISSUE THREAD

**Issue by tkivisik** [loov/goda#20]
There is a function sat8.
The good part is that the comment does explain the content of what it does. The improvable part is its naming. I propose it should either be renamed into something like `scaleTo256` or `scaleTo255`, or the documentation should expand with the explanation of what does the `sat8` stand for.

https://github.com/loov/goda/blob/master/graph/color.go#L54

**Comment by egonelbre** [comment]
`sat8` as in `saturate 8 bits`, see https://en.wikipedia.org/wiki/Saturation_arithmetic
