### ISSUE TITLE
Support build tags

### ISSUE THREAD

**Issue by howardjohn** [loov/goda#38]
Currently it seems build tags are not respected. I would like files like `// +build !bloat` to be ignored, since they will not end up in my final binaries anyways. Specifically with graph, but likely others apply as well

**Comment by howardjohn** [comment]
Seems like this is supported but I haven't figured out exactly how to do it. `goda graph -cluster -short 'tags=bloat(./...)'` is close I think, but doesn't seem to quite do it

**Comment by howardjohn** [comment]
aha, `'bloat=1(./...)'` seems to do it! The readme mentions this but I think its for a special case of test=1 not tags

**Comment by egonelbre** [comment]
Ah, yes, I did add the feature, but forgot to update the documentation.
