### ISSUE TITLE
expr: provide a way to select main packages

### ISSUE THREAD

**Issue by rogpeppe** [loov/goda#50]
Main packages are by definition roots, but we usually don't want to remove them;
currently there's no way to make an expression that finds all sources that are _not_
main packages.

How about a `:main` qualifier that selects only main packages. Then I can do (for example):

    goda list ./...:source - ./...:main

to find all non-main source packages.

**Comment by egonelbre** [comment]
It's also possible to output that information in `-f` with `{{ .Name }}`, which would output `"main"` for a main package.
