### ISSUE TITLE
What does ~ mean at the end of a package in dependency tree ?

### ISSUE THREAD

**Issue by SkybuckFlying** [loov/goda#76]
└ google.golang.org/protobuf/reflect/protoreflect
                  ├ google.golang.org/protobuf/encoding/protowire ~
                  └ google.golang.org/protobuf/internal/pragma

**Comment by egonelbre** [comment]
The `~` simply indicates that the dependencies have been already listed above. This is to reduce the huge amount of duplication in the listing.
