### ISSUE TITLE
Capture output for better analysis?

### ISSUE THREAD

**Issue by marcelloh** [loov/goda#79]
I was using this:

# print stats while building a go program
```
go build -a --toolexec "goda exec" .
```

But when I do this :
```
go build -a --toolexec "goda exec" . > output.txt
```

There's no output. in the file.

Is there a way to capture the output into a file, so I can analyse it better?

**Comment by egonelbre** [comment]
go build outputs to stderr, so you can use:

```
go build -toolexec "goda exec" . 2> output.txt
```
